---
# NOTE: Use dashes (-) exclusively for tags and underscores (_) exclusively for destinations.
# submit_request_cpus its called in pulsar and in plain condor only request_cpus
destinations:
  ######################
  # BASIC DESTINATIONS #
  ######################
  basic_docker_destination:
    abstract: true
    params:
      docker_enabled: true
      docker_sudo: false
      docker_net: bridge
      docker_auto_rm: true
      docker_set_user: ''
      # $defaults expands to "$galaxy_root:ro,$tool_directory:ro,$job_directory:ro,$working_directory:rw,$default_file_path:rw"
      docker_volumes: '$_CONDOR_SCRATCH_DIR:rw,
        $defaults,
        /cvmfs/data.galaxyproject.org:ro,
        /data/twd01/galaxy_db/:rw'
      require_container: true
      submit_request_cpus: '{cores}'
      submit_request_memory: '{mem}G'
      outputs_to_working_directory: false
      container_monitor_result: callback
    context:
      latitude: 47.9990
      longitude: 7.8421

  basic_singularity_destination:
    abstract: true
    params:
      submit_request_cpus: '{cores}'
      submit_request_memory: '{mem}G'
      singularity_enabled: true
      singularity_volumes: '$_CONDOR_SCRATCH_DIR:rw,
        $job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw'
      singularity_default_container_id: '/cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011'
    context:
      latitude: 47.9990
      longitude: 7.8421

  #############################
  # LOCAL CONDOR DESTINATIONS #
  #############################

  condor_docker:
    inherits: basic_docker_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    scheduling:
      require:
        - docker

  condor_singularity:
    inherits: basic_singularity_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
    scheduling:
      require:
        - singularity

  # Generic destination for tools that don't get any params
  # and no specified dependency resolution
  condor_tpv:
    runner: condor
    params:
      metadata_strategy: extended
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    scheduling:
      prefer:
        - condor-tpv
    context:
      latitude: 47.9990
      longitude: 7.8421

  condor_singularity_with_conda:
    inherits: basic_singularity_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
      require_container: true
      container:
        - type: singularity
          shell: '/bin/bash'
          resolve_dependencies: true
          identifier: '/cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011'
    scheduling:
      require:
        - singularity
        - conda

    #######################
  # PULSAR DESTINATIONS #
  #######################

  pulsar_default: # use for remote Pulsar nodes and ALWAYS overwrite the runner.
    abstract: true
    runner: pulsar_embedded
    env:
      LC_ALL: C
      SINGULARITY_CACHEDIR: /data/share/var/database/container_cache # On the NFS share on remote Pulsar side
    params:
      jobs_directory: /data/share/staging
      transport: curl
      remote_metadata: "false"
      metadata_strategy: directory
      default_file_action: remote_transfer
      rewrite_parameters: "true"
      persistence_directory: /data/share/persisted_data
      outputs_to_working_directory: "false"
      dependency_resolution: "none"
      submit_request_cpus: "{cores}"
      submit_request_memory: "{mem}"
      docker_volumes: "$job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw,
        /cvmfs/data.galaxyproject.org:ro"
      singularity_volumes: "$job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw,
        /cvmfs/data.galaxyproject.org:ro"
      singularity_enabled: true
      singularity_default_container_id: "/cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011"
    scheduling:
      accept:
        - pulsar
        - conda
        - singularity
        - docker
        - condor-tpv

  # pulsar_sanjay_tpv:
  #   inherits: pulsar_default
  #   runner: pulsar_sanjay_runner
  #   max_accepted_cores: 8
  #   max_accepted_mem: 15
  #   min_accepted_gpus: 0
  #   max_accepted_gpus: 0
  #   env:
  #     SINGULARITY_CACHEDIR: "/pulsar_data/container_cache"
  #   params:
  #     jobs_directory: "/pulsar_data/staging/ps01"
  #     persistence_directory: "/pulsar_data/persisted_data/ps01"
  #     metadata_strategy: extended
  #     tool_evaluation_strategy: remote
  #   scheduling:
  #     require:
  #       - sanjay-pulsar

  pulsar_de01:
    inherits: pulsar_default
    runner: pulsar_de01
    max_accepted_cores: 8
    max_accepted_mem: 15
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    env:
      SINGULARITY_CACHEDIR: "/pulsar_data/container_cache"
    params:
      jobs_directory: "/pulsar_data/staging/ps01"
      persistence_directory: "/pulsar_data/persisted_data/ps01"
      metadata_strategy: extended
    scheduling:
      require:
        - pulsar_de01
    context:
      latitude: 47.9990
      longitude: 7.8421

  pulsar_be01:
    inherits: pulsar_default
    runner: pulsar_be01
    max_accepted_cores: 8
    max_accepted_mem: 15
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    env:
      SINGULARITY_CACHEDIR: "/data/share/var/database/container_cache"
    params:
      jobs_directory: "/data/share/esg/staging"
      persistence_directory: "/data/share/esg/persisted_data"
      metadata_strategy: extended
    scheduling:
      require:
        - pulsar_be01
    context:
      latitude: 51.0179
      longitude: 3.6940


  ################################
  # EMBEDDED PULSAR DESTINATIONS #
  ################################

  embedded_pulsar_tpv:
    runner: pulsar_embedded
    params:
      metadata_strategy: extended
      # tool_evaluation_strategy: remote
    max_accepted_cores: 8
    max_accepted_mem: 15
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    scheduling:
      require:
        - pulsar-tpv
    context:
      latitude: 47.9990
      longitude: 7.8421
